# Generated by Django 4.2.7 on 2023-11-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='github',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='telegram',
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('link', models.URLField(blank=True)),
                ('logo', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='profiles.contact')),
            ],
            options={
                'db_table': 'social_networks',
            },
        ),
    ]
