# Generated by Django 4.2.7 on 2023-11-24 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_remove_contact_github_remove_contact_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='networks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
