# Generated by Django 4.2.7 on 2023-11-24 11:31

import apps.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_socialnetwork_contact_alter_socialnetwork_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.URLField(blank=True, unique=True, validators=[apps.profiles.validators.SocialNetworkValidator]),
        ),
    ]
