# Generated by Django 4.2.7 on 2023-11-24 13:08

import apps.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_socialnetwork_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='contact',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.URLField(blank=True, unique=True, validators=[apps.profiles.validators.SocialNetworkValidator()]),
        ),
    ]
