# Generated by Django 4.2.7 on 2023-11-27 20:20

import apps.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_contact_socialnetwork_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.URLField(blank=True, validators=[apps.profiles.validators.SocialNetworkValidator()]),
        ),
    ]
