# Generated by Django 4.2.7 on 2023-11-27 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_alter_socialnetwork_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialnetwork',
            unique_together={('name', 'user')},
        ),
    ]
