# Generated by Django 4.2.7 on 2023-11-26 20:23

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(600)]),
        ),
    ]
