# Generated by Django 4.2.7 on 2023-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
