# Generated by Django 4.2.7 on 2023-11-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
