version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - './env/.env.prod'
    ports:
      - '5432:${POSTGRES_PORT}'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      dockerfile: docker/app.prod.Dockerfile
      context: .
    container_name: app
    expose:
    - 8000
    restart: always
    volumes:
      - static_files:/home/project/app/staticfiles
    depends_on:
      - postgres
  
  nginx:
    build: ./deploy/nginx
    ports:
      - 1337:80
    volumes:
      - static_files:/home/project/app/staticfiles
    depends_on:
      - app

volumes:
  postgres_data:
  static_files: